trigger:
  batch: true
  branches:
    include:
    - master
    - release/*
  paths:
    exclude:
    - BUILDING.md
    - README.md

pr:
  branches:
    include:
    - master
    - release/*

variables:
  SolutionFile: 'src/ChildProcess.sln'

jobs:
- job: build

  pool:
    vmImage: 'windows-2019'

  steps:
  - task: PowerShell@2
    displayName: 'Set Variables'
    inputs:
      targetType: 'filePath'
      failOnStderr: true
      filePath: '$(Build.SourcesDirectory)/build/SetAzurePipelineVariables.ps1'
      arguments: '-CommitHash $(Build.SourceVersion) -BranchName $(Build.SourceBranchName)'

  - task: UseDotNet@2
    displayName: 'Use .NET Core SDK 3.1.101'
    inputs:
      packageType: sdk
      version: 3.1.101

  - task: DotNetCoreCLI@2
    displayName: 'dotnet restore'
    inputs:
      command: restore
      projects: '$(SolutionFile)'
      verbosityRestore: Quiet

  - task: DotNetCoreCLI@2
    displayName: 'dotnet build'
    inputs:
      projects: '$(SolutionFile)'
      arguments: '$(CommonBuildOptions)'

  - task: DotNetCoreCLI@2
    displayName: 'dotnet test'
    inputs:
      command: test
      projects: src/ChildProcess.Test/ChildProcess.Test.csproj
      arguments: '$(CommonBuildOptions)'

  - task: NuGetToolInstaller@0
    displayName: 'Use NuGet 4.9.4'
    inputs:
      versionSpec: 4.9.4

  - task: NuGetCommand@2
    displayName: 'NuGet custom'
    inputs:
      command: custom
      arguments: 'pack -Verbosity quiet -ForceEnglishOutput -Version $(PackageVersion) -BasePath bin/ChildProcess/AnyCPU/Release -OutputDirectory bin/nupkg -Properties commitHash=$(Build.SourceVersion) build/nuspec/Asmichi.ChildProcess.nuspec'

  - task: CopyFiles@2
    displayName: 'Copy Files to: $(Build.artifactstagingdirectory)'
    inputs:
      SourceFolder: '$(system.defaultworkingdirectory)'
      Contents: 'bin/nupkg/*'
      TargetFolder: '$(Build.artifactstagingdirectory)'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    inputs:
      PathtoPublish: '$(Build.artifactstagingdirectory)'

  - task: NuGetCommand@2
    displayName: 'NuGet push'
    inputs:
      command: push
      packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg'
      nuGetFeedType: 'internal'
      publishVstsFeed: 'ChildProcessCI'
      allowPackageConflicts: true
