trigger:
  batch: true
  branches:
    include:
    - master
    - release/*
  paths:
    exclude:
    - BUILDING.md
    - README.md

pr:
  branches:
    include:
    - master
    - release/*

variables:
  SolutionFile: 'src/ChildProcess.sln'

jobs:
- job: build_native_linux

  pool:
    vmImage: 'ubuntu-18.04'

  container: 'asmichi/childprocess-buildtools-ubuntu-crosssysroot:18.04.20210612.1'

  steps:
  - task: Bash@3
    displayName: 'Build Native Linux'
    inputs:
      targetType: 'filePath'
      filePath: 'src/ChildProcess.Native/Subbuild-unix.sh'
      arguments: 'Linux obj/Subbuild-linux bin/ChildProcess.Native'

  - publish: 'bin/ChildProcess.Native'
    artifact: 'ChildProcess.Native-linux'

- job: build_native_osx

  pool:
    vmImage: 'macOS-10.15'

  steps:
  - task: Bash@3
    displayName: 'Build Native macOS'
    inputs:
      targetType: 'filePath'
      filePath: 'src/ChildProcess.Native/Subbuild-unix.sh'
      arguments: 'OSX obj/Subbuild-osx bin/ChildProcess.Native'

  - publish: 'bin/ChildProcess.Native'
    artifact: 'ChildProcess.Native-osx'

- job: build_native_win

  pool:
    vmImage: 'windows-2019'

  steps:
  - task: PowerShell@2
    displayName: 'Set VSDEVCMD_LOCATION'
    inputs:
      pwsh: true
      targetType: 'filePath'
      failOnStderr: true
      filePath: '$(Build.SourcesDirectory)/build/SetVsDevCmdLocation.ps1'

  - task: BatchScript@1
    displayName: 'Call VsDevCmd.bat'
    inputs:
      filename: '$(VSDEVCMD_LOCATION)'
      arguments: '-no_logo -arch=amd64 -host_arch=amd64'
      failOnStderr: true
      modifyEnvironment: true

  - task: PowerShell@2
    displayName: 'Build Native Windows'
    inputs:
      pwsh: true
      targetType: 'filePath'
      filePath: 'src/ChildProcess.Native/Subbuild-win.ps1'
      arguments: '$(Build.SourcesDirectory)'

  - publish: 'bin/ChildProcess.Native'
    artifact: 'ChildProcess.Native-win'

- job: build_and_pack

  dependsOn:
    - build_native_linux
    - build_native_osx
    - build_native_win

  pool:
    vmImage: 'ubuntu-18.04'

  steps:
  - template: 'build/prepare-variables.yml'
  - template: 'build/prepare-dotnet.yml'

  - task: DownloadPipelineArtifact@2
    inputs:
      source: current
      artifact: 'ChildProcess.Native-linux'
      path: '$(Build.SourcesDirectory)/bin/ChildProcess.Native'

  - task: DownloadPipelineArtifact@2
    inputs:
      source: current
      artifact: 'ChildProcess.Native-osx'
      path: '$(Build.SourcesDirectory)/bin/ChildProcess.Native'

  - task: DownloadPipelineArtifact@2
    inputs:
      source: current
      artifact: 'ChildProcess.Native-win'
      path: '$(Build.SourcesDirectory)/bin/ChildProcess.Native'

  - task: DotNetCoreCLI@2
    displayName: 'dotnet build'
    inputs:
      projects: '$(SolutionFile)'
      arguments: '$(CommonBuildOptions)'
      verbosityRestore: Quiet

  - task: NuGetToolInstaller@0
    displayName: 'Use NuGet 5.8.1'
    inputs:
      versionSpec: 5.8.1

  - task: DotNetCoreCLI@2
    displayName: 'dotnet pack'
    inputs:
      command: custom
      custom: pack
      arguments: '$(Build.SourcesDirectory)/src/ChildProcess/ChildProcess.csproj $(CommonBuildOptions) --output $(Build.ArtifactStagingDirectory)'

  - task: NuGetCommand@2
    displayName: 'NuGet push'
    inputs:
      command: push
      packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;$(Build.ArtifactStagingDirectory)/**/*.snupkg'
      allowPackageConflicts: true
      configurationToPack: 'Release'
      nuGetFeedType: 'internal'
      publishVstsFeed: 'ChildProcess/CI'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'

  - task: DotNetCoreCLI@2
    displayName: 'dotnet build'
    inputs:
      projects: '$(SolutionFile)'
      arguments: '$(CommonBuildOptions) -p:AddImportSearchPathAssemblyDirectory=true' # Workaround for https://github.com/dotnet/sdk/issues/1088
      verbosityRestore: Quiet

  - publish: 'bin/ChildProcess.Test'
    artifact: 'ChildProcess.Test'

- job: test_linux_x64

  dependsOn:
    - build_and_pack
    - build_native_linux

  pool:
    vmImage: 'ubuntu-18.04'

  steps:
  - template: 'build/test.yml'
    parameters:
      platform: linux
      rid: linux-x64

- job: test_osx_x64

  dependsOn:
    - build_and_pack
    - build_native_osx

  pool:
    vmImage: 'macOS-10.15'

  steps:
  - template: 'build/test.yml'
    parameters:
      platform: osx
      rid: osx-x64

- job: test_win_x64

  dependsOn:
    - build_and_pack
    - build_native_win

  pool:
    vmImage: 'windows-2019'

  steps:
  - template: 'build/test.yml'
    parameters:
      platform: win
      rid: win-x64
