trigger:
  batch: true
  branches:
    include:
    - master
    - release/*
  paths:
    exclude:
    - BUILDING.md
    - README.md

pr:
  branches:
    include:
    - master
    - release/*

variables:
  SolutionFile: 'src/ChildProcess.sln'

jobs:
- job: build_linux

  continueOnError: true # Work around https://github.com/dotnet/sdk/issues/13431

  pool:
    vmImage: 'ubuntu-18.04'

  steps:
  - template: 'build/prepare-job.yml'

  - script: 'sudo apt-get install -qq -y ninja-build'

  - task: Bash@3
    inputs:
      targetType: 'filePath'
      filePath: 'src/ChildProcess.Native/Subbuild-linux.sh'
      arguments: 'obj/Subbuild-linux'

  - task: CopyFiles@2
    inputs:
      SourceFolder: 'obj/Subbuild-linux/bin/linux-x64/Release'
      Contents: '**'
      TargetFolder: 'bin/ChildProcess.Native/linux-x64/Release'

  - publish: 'obj/Subbuild-linux/bin/linux-x64'
    artifact: 'ChildProcess.Native-linux-x64'

  - template: 'build/build-and-test.yml'
    parameters:
      platform: linux
      additionalArguments: '-p:AddImportSearchPathAssemblyDirectory=true' # Workaround for https://github.com/dotnet/sdk/issues/1088

- job: build

  dependsOn: build_linux

  pool:
    vmImage: 'windows-2019'

  steps:
  - template: 'build/prepare-job.yml'

  - task: DownloadPipelineArtifact@2
    inputs:
      source: current
      artifact: 'ChildProcess.Native-linux-x64'
      path: '$(Build.SourcesDirectory)/bin/ChildProcess.Native/linux-x64'

  - template: 'build/build-and-test.yml'
    parameters:
      platform: win

  - task: NuGetToolInstaller@0
    displayName: 'Use NuGet 5.7.0'
    inputs:
      versionSpec: 5.7.0

  - task: DotNetCoreCLI@2
    displayName: 'dotnet pack'
    inputs:
      command: custom
      custom: pack
      arguments: '$(Build.SourcesDirectory)/src/ChildProcess/ChildProcess.csproj $(CommonBuildOptions) --output $(Build.ArtifactStagingDirectory)'

  - task: NuGetCommand@2
    displayName: 'NuGet push'
    inputs:
      command: push
      packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;$(Build.ArtifactStagingDirectory)/**/*.snupkg'
      allowPackageConflicts: true
      configurationToPack: 'Release'
      nuGetFeedType: 'internal'
      publishVstsFeed: 'ChildProcess/CI'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
